[ADD]: elt of new repo

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,96 +1,125 @@
-name: Chocolotine
+name: Chocolatine
+ 
 on:
-  push:
-    branches-ignore:
-      - 'ga-ignore-*'
-  pull_request:
-    branches-ignore:
-      - 'ga-ignore-*'
+   push:
+     branches-ignore:
+       - 'ga-ignore-**'
+   pull_request:
+     branches-ignore:
+       - 'ga-ignore-**'
  
 env:
-  MIRROR_URL: ${{ secrets.git@github.com:EpitechPGEPromo2029/B-DOP-200-BDX-2-1-chocolatine-salah-eddine.ghellab.git}}
-  EXECUTABLES: "my_printf"
+   MIRROR_URL: Salah-eddine23/Chocolatine.git
+   EXECUTABLES: my_printf
  
 jobs:
-  check_repository:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check if we're in the mirror repository
-        id: check_mirror
-        run: |
-          if [ "$GITHUB_REPOSITORY" == "${{ secrets.MIRROR_REPO_NAME }}" ]; then
-            echo "We are in the mirror repository, skipping all jobs."
-            exit 0
-          fi
-    outputs:
-      skip: ${{ steps.check_mirror.outputs.skip }}
  
   check_coding_style:
-    name: Check Coding Style
-    runs-on: ubuntu-latest
-    needs: check_repository
-    container: ghcr.io/epitech/coding-style-checker:latest
+     name: Checking coding-style
+     runs-on: ubuntu-latest
+ 
+    container:
+       image: ghcr.io/epitech/coding-style-checker:latest
+     if: ${{ github.repository != 'Salah-eddine23/Chocolatine' }}
+ 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Run coding style check
-        run: check.sh $(pwd) $(pwd)
-      - name: Display coding style errors
-        run: |
-          if [ -f coding-style-reports.log ]; then
-            cat coding-style-reports.log
-            while IFS= read -r line; do
-              echo "::error file=$(echo $line | cut -d: -f1),line=$(echo $line | cut -d: -f2),title=Coding Style Error::$(echo $line | cut -d: -f3-)"
-            done < coding-style-reports.log
-            exit 0
-          fi
+ 
+      - name: Checkout Repository
+         uses: actions/checkout@v4
+ 
+      - name: Check Coding Style
+         run: check.sh $(pwd) $(pwd)
+ 
+      - name: Report banana result
+         run: |
+           NB_ERROR=$(cat coding-style-reports.log | wc -l)
+           if [ $NB_ERROR -gt 0 ]; then
+             ERRORS=$(cat coding-style-reports.log);
+             echo "Banana found $NB_ERROR error(s)"
+             echo "$ERRORS"
+             while IFS= read -r line || [-n "$line"]; do
+               echo "::error::$line"
+             done < coding-style-reports.log
+             exit 1
+           fi
+             echo "Everything is good ! Keep on coding !"
+             exit 0
  
   check_program_compilation:
-    name: Check Program Compilation
-    runs-on: ubuntu-latest
-    needs: check_coding_style
-    container: epitechcontent/epitest-docker
+     name: Checking program compilation
+     runs-on: ubuntu-latest
+     needs: [check_coding_style]
+ 
+    container:
+       image: ghcr.io/epitech/coding-style-checker:latest
+ 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Compile program
-        timeout-minutes: 2
-        run: make
-      - name: Clean compilation
-        run: make clean
-      - name: Verify executables
-        run: |
-          IFS=',' read -ra EXECS <<< "$EXECUTABLES"
-          for exec in "${EXECS[@]}"; do
-            if [ ! -x "$exec" ]; then
-              echo "::error title=Missing Executable::Executable '$exec' not found or not executable"
-              exit 0
-            fi
-          done
+       - name: Checkout repository
+         uses: actions/checkout@v4
+ 
+      - name: Compile project
+         run: make
+         timeout-minutes: 2
+ 
+      - name: Check executable files
+         run: |
+           if [ ! -f "$EXECUTABLES" ]; then
+             echo "::error::Error:file $EXECTABLES not found"
+             exit 1
+           fi
+       - name: Clean project
+         run: make clean
  
   run_tests:
-    name: Run Tests
-    runs-on: ubuntu-latest
-    needs: check_program_compilation
-    container: epitechcontent/epitest-docker
+     name: Running tests
+     runs-on: ubuntu-latest
+ 
+    container:
+       image: epitechcontent/epitest-docker:latest
+     needs: [check_program_compilation]
+     if: ${{ success() && github.repository != 'Salah-eddine23/Chocolatine' }}
+ 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+       - name: Checkout repository
+         uses: actions/checkout@v4
+ 
       - name: Run tests
-        timeout-minutes: 2
-        run: make tests_run
+         run: make tests_run
+         timeout-minutes: 2
  
   push_to_mirror:
-    name: Push to Mirror Repository
-    runs-on: ubuntu-latest
-    needs: run_tests
-    if: github.event_name == 'push'
+     name: Pushing to mirror repository
+     runs-on: ubuntu-latest
+ 
+    needs: [run_tests]
+     if: github.event_name == 'push'
+ 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-      - name: Push to Mirror
-        uses: pixta-dev/repository-mirroring-action@v1
-        with:
-          target_repo_url: "${{ env.git@github.com:EpitechPGEPromo2029/B-DOP-200-BDX-2-1-chocolatine-salah-eddine.ghellab.git }}"
-          ssh_private_key: "${{ secrets.GIT_SSH_PRIVATE_KEY }}"
-
+       - name: Checkout repository
+         uses: actions/checkout@v4
+         with:
+           fetch-depth: 0
+ 
+      - name: Push to mirror
+         uses: pixta-dev/repository-mirroring-action@v1
+         with:
+           target_repo_url: ${{ env.MIRROR_URL }}
+           ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+ 
+  from_source:
+     name: Mirror from source
+     runs-on: ubuntu-latest
+ 
+    needs: [run_tests]
+ 
+    steps:
+       - name: Checkout repository
+         uses: actions/checkout@v4
+         with:
+           fetch-depth: 0
+ 
+      - name: src chocolatine
+         uses: pixta-dev/repository-mirroring-action@v1
+         with:
+           target_repo_url: git@github.com:Salah-eddine23/Chocolatine.git
+           ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
